import { Policies } from "@/lib/auth/action-policy";
import { renderHtmlToPdf } from "@/lib/documents/playwright-pdf";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

export default async function PdfHealthPage() {
  await Policies.companySettings();
  const startedAt = Date.now();

  try {
    const pdf = await renderHtmlToPdf(
      "<!doctype html><html><body><h1>HASA Concepts</h1><p>PDF renderer health check.</p></body></html>"
    );
    const ready = pdf.bytes.length > 100;

    return (
      <section>
        <div className="page-heading">
          <div>
            <h1>PDF Renderer Health</h1>
            <p>Owner-only, read-only production diagnostic.</p>
          </div>
        </div>
        <div className="panel">
          <h2>{ready ? "PDF renderer ready" : "PDF renderer unavailable"}</h2>
          <p>Generated bytes: {pdf.bytes.length.toLocaleString()}</p>
          <p>SHA-256: {pdf.sha256}</p>
          <p>Duration: {Date.now() - startedAt} ms</p>
        </div>
      </section>
    );
  } catch (error) {
    console.error("[pdf-health-page] failed", {
      message: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    });

    return (
      <section>
        <div className="page-heading">
          <div>
            <h1>PDF Renderer Health</h1>
            <p>Owner-only, read-only production diagnostic.</p>
          </div>
        </div>
        <div className="panel">
          <h2>PDF renderer unavailable</h2>
          <p>The health check failed. Review the production runtime log for details.</p>
        </div>
      </section>
    );
  }
}
