"use client";

import Image from "next/image";
import type { FormEvent } from "react";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type MfaFormProps = {
  mode: "enroll" | "challenge";
  verifiedFactorId?: string;
};

type EnrollmentDetails = {
  factorId: string;
  qrCode: string;
  secret: string;
};

export function MfaForm({ mode, verifiedFactorId }: MfaFormProps) {
  const router = useRouter();
  const initializationStarted = useRef(false);
  const [enrollment, setEnrollment] = useState<EnrollmentDetails | null>(null);
  const [code, setCode] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(mode === "enroll");

  useEffect(() => {
    if (mode !== "enroll" || initializationStarted.current) return;
    initializationStarted.current = true;

    async function beginEnrollment() {
      setBusy(true);
      setMessage("");

      const { data: factors, error: factorsError } =
        await supabase.auth.mfa.listFactors();

      if (factorsError) {
        setMessage("Authenticator setup could not be started. Please sign out and try again.");
        setBusy(false);
        return;
      }

      if (factors.totp.some((factor) => factor.status === "verified")) {
        router.refresh();
        return;
      }

      for (const factor of factors.totp.filter(
        (candidate) => candidate.status !== "verified"
      )) {
        const { error } = await supabase.auth.mfa.unenroll({
          factorId: factor.id,
        });
        if (error) {
          setMessage("A previous authenticator setup could not be cleared. Please sign out and try again.");
          setBusy(false);
          return;
        }
      }

      const { data, error } = await supabase.auth.mfa.enroll({
        factorType: "totp",
        friendlyName: "HASA Concepts Management",
        issuer: "HASA Concepts",
      });

      if (error) {
        setMessage("Authenticator setup could not be created. Please sign out and try again.");
        setBusy(false);
        return;
      }

      setEnrollment({
        factorId: data.id,
        qrCode: data.totp.qr_code,
        secret: data.totp.secret,
      });
      setBusy(false);
    }

    void beginEnrollment();
  }, [mode, router]);

  async function verifyCode(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const normalizedCode = code.replace(/\s/g, "");

    if (!/^\d{6}$/.test(normalizedCode)) {
      setMessage("Enter the six-digit code shown in your authenticator app.");
      return;
    }

    const factorId =
      mode === "challenge" ? verifiedFactorId : enrollment?.factorId;
    if (!factorId) {
      setMessage("Authenticator verification is not ready. Please try again.");
      return;
    }

    setBusy(true);
    setMessage("");

    const { data: challenge, error: challengeError } =
      await supabase.auth.mfa.challenge({ factorId });

    if (challengeError) {
      setMessage("A verification challenge could not be created. Please try again.");
      setBusy(false);
      return;
    }

    const { error: verifyError } = await supabase.auth.mfa.verify({
      factorId,
      challengeId: challenge.id,
      code: normalizedCode,
    });

    if (verifyError) {
      setMessage("That code was not accepted. Wait for a new code and try again.");
      setBusy(false);
      return;
    }

    router.replace("/dashboard");
    router.refresh();
  }

  return (
    <div className="mfa-form">
      {mode === "enroll" ? (
        <>
          <ol className="mfa-instructions">
            <li>Open an authenticator app, such as Microsoft Authenticator, Google Authenticator, or 1Password.</li>
            <li>Scan this QR code.</li>
            <li>Enter the six-digit code generated by the app.</li>
          </ol>
          {enrollment ? (
            <>
              <div className="mfa-qr">
                <Image
                  src={enrollment.qrCode}
                  alt="QR code for HASA Concepts Management"
                  width={220}
                  height={220}
                  unoptimized
                />
              </div>
              <details className="mfa-secret">
                <summary>Cannot scan the QR code?</summary>
                <p>Enter this setup key manually:</p>
                <code>{enrollment.secret}</code>
              </details>
            </>
          ) : null}
        </>
      ) : (
        <p className="mfa-prompt">
          Enter the current six-digit code from your authenticator app.
        </p>
      )}

      <form className="login-form" onSubmit={verifyCode}>
        <label>
          Verification code
          <input
            name="code"
            type="text"
            inputMode="numeric"
            autoComplete="one-time-code"
            pattern="[0-9]{6}"
            maxLength={6}
            value={code}
            onChange={(event) => setCode(event.target.value)}
            disabled={busy || (mode === "enroll" && !enrollment)}
            required
            autoFocus={mode === "challenge"}
          />
        </label>
        {message ? (
          <p className="form-message error" role="alert">
            {message}
          </p>
        ) : null}
        <button
          className="primary-button"
          type="submit"
          disabled={busy || (mode === "enroll" && !enrollment)}
        >
          {busy ? "Please wait..." : mode === "enroll" ? "Enable MFA" : "Verify and Continue"}
        </button>
      </form>
    </div>
  );
}
